[language-server.clangd]
command = "clangd"

[language-server.zls]
command = "~/.dev/LSPs/zls/zls"

[language-server.sourcekit-lsp]
command = "sourcekit-lsp"

[language-server.pyright]
command = "pyright"

[[language]]
name = "cpp"
auto-format = true
file-types = ["cpp", "cc", "hxx", "h", "hpp"]
language-servers = ["clangd"]

[[language]]
name = "python"
auto-format = true
language-servers = ["pyright"]

